version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    reviewers:
      - Limerio
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - Limerio
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - Limerio
  - package-ecosystem: "terraform"
    directories:
      - "infrastructure/terraform"
    schedule:
      interval: "weekly"
    reviewers:
      - Limerio
