/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ServicesImport } from './routes/services'
import { Route as ServicesServiceIdImport } from './routes/services.$serviceId'

// Create Virtual Routes

const SignUpLazyImport = createFileRoute('/sign-up')()
const SignInLazyImport = createFileRoute('/sign-in')()
const ResetPasswordLazyImport = createFileRoute('/reset-password')()
const LegalLazyImport = createFileRoute('/legal')()
const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SignUpLazyRoute = SignUpLazyImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up.lazy').then((d) => d.Route))

const SignInLazyRoute = SignInLazyImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in.lazy').then((d) => d.Route))

const ResetPasswordLazyRoute = ResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)

const LegalLazyRoute = LegalLazyImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/legal.lazy').then((d) => d.Route))

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const ServicesRoute = ServicesImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServicesServiceIdRoute = ServicesServiceIdImport.update({
  id: '/$serviceId',
  path: '/$serviceId',
  getParentRoute: () => ServicesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalLazyImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdImport
      parentRoute: typeof ServicesImport
    }
  }
}

// Create and export the route tree

interface ServicesRouteChildren {
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceIdRoute: ServicesServiceIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/services': typeof ServicesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/services': typeof ServicesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/services': typeof ServicesRouteWithChildren
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/services'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/services'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/services'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  LegalLazyRoute: typeof LegalLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  SignInLazyRoute: typeof SignInLazyRoute
  SignUpLazyRoute: typeof SignUpLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  LegalLazyRoute: LegalLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  SignInLazyRoute: SignInLazyRoute,
  SignUpLazyRoute: SignUpLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/services",
        "/forgot-password",
        "/legal",
        "/reset-password",
        "/sign-in",
        "/sign-up"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/services": {
      "filePath": "services.tsx",
      "children": [
        "/services/$serviceId"
      ]
    },
    "/forgot-password": {
      "filePath": "forgot-password.lazy.tsx"
    },
    "/legal": {
      "filePath": "legal.lazy.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.lazy.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.lazy.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.lazy.tsx"
    },
    "/services/$serviceId": {
      "filePath": "services.$serviceId.tsx",
      "parent": "/services"
    }
  }
}
ROUTE_MANIFEST_END */
