/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ServicesIndexImport } from './routes/services/index'
import { Route as ServicesServiceIdImport } from './routes/services/$serviceId'

// Create Virtual Routes

const SignUpLazyImport = createFileRoute('/sign-up')()
const SignInLazyImport = createFileRoute('/sign-in')()
const ResetPasswordLazyImport = createFileRoute('/reset-password')()
const LegalLazyImport = createFileRoute('/legal')()
const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const CheckoutIndexLazyImport = createFileRoute('/checkout/')()
const CheckoutReturnLazyImport = createFileRoute('/checkout/return')()

// Create/Update Routes

const SignUpLazyRoute = SignUpLazyImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-up.lazy').then((d) => d.Route))

const SignInLazyRoute = SignInLazyImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/sign-in.lazy').then((d) => d.Route))

const ResetPasswordLazyRoute = ResetPasswordLazyImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)

const LegalLazyRoute = LegalLazyImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/legal.lazy').then((d) => d.Route))

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutIndexLazyRoute = CheckoutIndexLazyImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/checkout/index.lazy').then((d) => d.Route),
)

const ServicesIndexRoute = ServicesIndexImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRoute,
} as any)

const CheckoutReturnLazyRoute = CheckoutReturnLazyImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/checkout/return.lazy').then((d) => d.Route),
)

const ServicesServiceIdRoute = ServicesServiceIdImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalLazyImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInLazyImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdImport
      parentRoute: typeof rootRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnLazyImport
      parentRoute: typeof rootRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutIndexLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/checkout/return': typeof CheckoutReturnLazyRoute
  '/services': typeof ServicesIndexRoute
  '/checkout': typeof CheckoutIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/checkout/return': typeof CheckoutReturnLazyRoute
  '/services': typeof ServicesIndexRoute
  '/checkout': typeof CheckoutIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/legal': typeof LegalLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/sign-in': typeof SignInLazyRoute
  '/sign-up': typeof SignUpLazyRoute
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/checkout/return': typeof CheckoutReturnLazyRoute
  '/services/': typeof ServicesIndexRoute
  '/checkout/': typeof CheckoutIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
    | '/checkout/return'
    | '/services'
    | '/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
    | '/checkout/return'
    | '/services'
    | '/checkout'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/services/$serviceId'
    | '/checkout/return'
    | '/services/'
    | '/checkout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
  LegalLazyRoute: typeof LegalLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  SignInLazyRoute: typeof SignInLazyRoute
  SignUpLazyRoute: typeof SignUpLazyRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  CheckoutReturnLazyRoute: typeof CheckoutReturnLazyRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  CheckoutIndexLazyRoute: typeof CheckoutIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
  LegalLazyRoute: LegalLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  SignInLazyRoute: SignInLazyRoute,
  SignUpLazyRoute: SignUpLazyRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  CheckoutReturnLazyRoute: CheckoutReturnLazyRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  CheckoutIndexLazyRoute: CheckoutIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forgot-password",
        "/legal",
        "/reset-password",
        "/sign-in",
        "/sign-up",
        "/services/$serviceId",
        "/checkout/return",
        "/services/",
        "/checkout/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.lazy.tsx"
    },
    "/legal": {
      "filePath": "legal.lazy.tsx"
    },
    "/reset-password": {
      "filePath": "reset-password.lazy.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.lazy.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.lazy.tsx"
    },
    "/services/$serviceId": {
      "filePath": "services/$serviceId.tsx"
    },
    "/checkout/return": {
      "filePath": "checkout/return.lazy.tsx"
    },
    "/services/": {
      "filePath": "services/index.tsx"
    },
    "/checkout/": {
      "filePath": "checkout/index.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
