name: CD

on:
  push:
    branches:
      - main

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun i
      - name: Build applications
        run: bun run build
  build-api:
    runs-on: ubuntu-latest
    needs:
      - build-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: API docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: api
          context: ./apps/api
  build-landing:
    runs-on: ubuntu-latest
    needs:
      - build-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Landing docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: landing
          context: ./apps/landing
  build-admin:
    runs-on: ubuntu-latest
    needs:
      - build-code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Admin docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: admin
          context: ./apps/admin
