name: CD

on:
  push:
    branches:
      - main

jobs:
  build-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install
        run: bun i
      - name: Build applications
        run: bun run build
      - name: API docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: api
      - name: Landing docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: landing
      - name: Admin docker Build
        uses: ./.github/actions/docker
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          image: admin
