name: Terraform CI

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/terraform/**"
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/terraform/**"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infrastructure/terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.0

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: |
          for dir in $(find . -type f -name "*.tf" -not -path "*/\.*" | xargs -I{} dirname {} | sort -u); do
            echo "Initializing Terraform in $dir"
            cd $GITHUB_WORKSPACE/infrastructure/terraform/$(echo $dir | sed 's|^./||')
            terraform init -backend=false
          done

      - name: Terraform Validate
        run: |
          for dir in $(find . -type f -name "*.tf" -not -path "*/\.*" | xargs -I{} dirname {} | sort -u); do
            echo "Validating Terraform in $dir"
            cd $GITHUB_WORKSPACE/infrastructure/terraform/$(echo $dir | sed 's|^./||')
            terraform validate
          done

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          for dir in $(find . -type f -name "*.tf" -not -path "*/\.*" | xargs -I{} dirname {} | sort -u); do
            echo "Planning Terraform in $dir"
            cd $GITHUB_WORKSPACE/infrastructure/terraform/$(echo $dir | sed 's|^./||')
            terraform plan -no-color -input=false
          done
        continue-on-error: true
